### ISSUE TITLE
FormatException (FormatException: Invalid empty scheme (at character 1)

### ISSUE THREAD

**Issue by BartusZak** [arnemolland/sigv4#27]
`sign` extenstion does not work in `example.dart`.

 ``` dart
Request('GET', Uri.parse(path)).sign(client);
````

<details>
<summary>Exception</summary>

```
Unhandled exception:
FormatException: Invalid empty scheme (at character 1)
://
^

#0      _Uri._fail (dart:core/uri.dart:1538:5)
#1      new _Uri.notSimple (dart:core/uri.dart:1371:9)
#2      Uri.parse (dart:core/uri.dart:956:17)
#3      Sigv4Client.signedHeaders
package:sigv4/src/client.dart:137
#4      HttpExtension.sign
package:sigv4/…/extensions/http.dart:6
#5      main
package:sigv4/main.dart:56

#6      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

```
</details>

**Comment by MohammedNoureldin** [comment]
Same here, have you found any solution?

**Comment by BartusZak** [comment]
Hey @MohammedNoureldin,

No, I did not.

I used a standard solution and sign it manually with `interceptors`.

```dart
 CognitoDioClient({required authenticationRepository})
      : _authenticationRepository = authenticationRepository,
        assert(authenticationRepository != null) {
    _cognitoDioClient.options.baseUrl = serverUrl;

    _cognitoDioClient.interceptors
        .add(InterceptorsWrapper(onRequest: (options, handler) {
      final String? idToken = _sharedPreferencesManager!.getString('idToken');

      options.headers[HttpHeaders.authorizationHeader] = 'Bearer $idToken';
      return handler.next(options);
    }, onResponse: (response, handler) {
      return handler.next(response);
    }, onError: (DioError e, handler) async {
      // Do something with response error
      _cognitoDioClient.lock();
      _cognitoDioClient.interceptors.responseLock.lock();
      _cognitoDioClient.interceptors.errorLock.lock();

      RequestOptions options = e.response!.requestOptions;

      final bool _isIdTokenValid =
          await _authenticationRepository.isIdTokenValid();

      if (!_isIdTokenValid) {
        try {
          await _authenticationRepository.refreshTokens();
        } catch (e) {
          print('Refresh Token failed');
        }
        _cognitoDioClient.request(options.path, options: options as Options?);
      }

      _cognitoDioClient.unlock();
      _cognitoDioClient.interceptors.responseLock.unlock();
      _cognitoDioClient.interceptors.errorLock.unlock();
      return handler.next(e);
    }));
```

Please keep in mind that storing a plain credentials in `Session or Local Storage` of the Browser is not recommended.
There should be an addictionel layer of security (`hashed/ encoded `or something).

Perfect solution (regarding to other articles) is to store credentials inside Cookie.

Be aware :)

**Comment by MohammedNoureldin** [comment]
@BartusZak I am bit confused. The code is not very clear to me. How is this supposed to sign URL/Headers? And why is it a *Standard* solution?

**Comment by MohammedNoureldin** [comment]
Whatever, I implemented my own Dart code that signs the AWS URLs:

https://github.com/MohammedNoureldin/aws-url-signer
